server:
  port: 8090

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://13.209.18.95:3306/easyplan
    username: ENC(mkER2TW49E8B9Rh9XyCetQ==)
    password: ENC(n5o33/cX22FQzUWpscI0qA==)

  jpa:
    properties:
      hibernate:
        format_sql: true
        open-in-view: false

    hibernate:
      ddl-auto: create

    generate-ddl: true

  profiles:
    active: local
    include: oauth, secret

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(r/8+mz3c5C1RMiku4W4Uf3mqAVRCAGKqg5L3q8MYBSc=)
    password: ENC(OVrcZbxjgLUcqjZsyjGhQZwaI8qASznESOG/QVS63h4=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

jwt:
  header:
    Authorization
  secret:
    c2Vva3llb25nLW5pdmVyc2l0eS1jbG91ZC1iYWNrZW5kLWNsYXNzLXRlYW0tcHJvamVjdC1lYXN5LXBsYW4tc2VjcmV0LWtleQ==
  token-validity-in-seconds:
    86400

  file:
    upload-dir: "C:/hss/upload"
    web-dir: "/uploads/"


    servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

openai:
  api:
    key: ENC(PdkR3XzQMKtIFK3AADsD+R/PD+TW8vmUo0i1P+ODDoy2HKNvTiymsYaVrHOukdHPQzg6kIzGXlnLV5Um8A8vf+YprDhOSphI)
    url: https://api.openai.com/v1/chat/completions
  model: gpt-4o