spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(hA2ax9rp3lpXzHVDEh7NnxWv75mqXgsHvRzelt78SHL67KeiCds14Sl4I2ZUeC9W)
            client-secret: ENC(jVGMiOlu8LysViQTKrfLdanXHx7MvvYrB2PCiRSFTxaL4OFRu0Azrns2zFYK7pRV)
            redirect-uri: "http://localhost:8090/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, talk_message

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id